Bootstrap the challenge for data-engineers
devsbb/grover-engineering-recruitment pull request #3
Opened 2022-02-25 13:38 UTC by nicor88

# What
Add a challenge for data-engineers.
The challenge provide a minimal setup to run faust locally, the aim is to have the candidate focusing on the requested assignments, not in wrapping up the setup.

2022-02-25 13:49 UTC, leanbc requested changes

2022-02-25 13:49 UTC, leanbc commented on challenges/faust-data-processing/app/wait_for_service.py
> +    """XXX: AL add docs."""
put doco or remove.

2022-02-25 13:49 UTC, leanbc commented on challenges/faust-data-processing/app/wait_for_service.py
> +    """XXX: AL add docs."""
put doco or remove.

2022-03-03 14:10 UTC, vertexclique approved these changes

2022-03-03 14:10 UTC, vertexclique approved these changes

2022-03-04 15:43 UTC, mermi approved these changes
LGTM

2022-03-10 17:51 UTC, merged